// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/afs-public/ascend-sdk-go/models/components"
)

type AccountsCreateLegalNaturalPersonResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	LegalNaturalPerson *components.LegalNaturalPerson
	// INVALID_ARGUMENT: The request is not valid, additional information may be present in the BadRequest details.
	Status *components.Status
}

func (o *AccountsCreateLegalNaturalPersonResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AccountsCreateLegalNaturalPersonResponse) GetLegalNaturalPerson() *components.LegalNaturalPerson {
	if o == nil {
		return nil
	}
	return o.LegalNaturalPerson
}

func (o *AccountsCreateLegalNaturalPersonResponse) GetStatus() *components.Status {
	if o == nil {
		return nil
	}
	return o.Status
}
