// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ascend-sdk/models/components"
)

type AccountsEndLargeTrader1Request struct {
	// The legalEntity id.
	LegalEntityID               string                                 `pathParam:"style=simple,explode=false,name=legalEntity_id"`
	EndLargeTraderRequestCreate components.EndLargeTraderRequestCreate `request:"mediaType=application/json"`
}

func (o *AccountsEndLargeTrader1Request) GetLegalEntityID() string {
	if o == nil {
		return ""
	}
	return o.LegalEntityID
}

func (o *AccountsEndLargeTrader1Request) GetEndLargeTraderRequestCreate() components.EndLargeTraderRequestCreate {
	if o == nil {
		return components.EndLargeTraderRequestCreate{}
	}
	return o.EndLargeTraderRequestCreate
}

type AccountsEndLargeTrader1Response struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// INVALID_ARGUMENT: The request is not valid, additional information may be present in the BadRequest details.
	Status *components.Status
}

func (o *AccountsEndLargeTrader1Response) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AccountsEndLargeTrader1Response) GetStatus() *components.Status {
	if o == nil {
		return nil
	}
	return o.Status
}
