// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/afs-public/ascend-sdk-go/models/components"
)

type AchDepositsForceApproveAchDepositRequest struct {
	// The account id.
	AccountID string `pathParam:"style=simple,explode=false,name=account_id"`
	// The achDeposit id.
	AchDepositID                        string                                         `pathParam:"style=simple,explode=false,name=achDeposit_id"`
	ForceApproveAchDepositRequestCreate components.ForceApproveAchDepositRequestCreate `request:"mediaType=application/json"`
}

func (o *AchDepositsForceApproveAchDepositRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *AchDepositsForceApproveAchDepositRequest) GetAchDepositID() string {
	if o == nil {
		return ""
	}
	return o.AchDepositID
}

func (o *AchDepositsForceApproveAchDepositRequest) GetForceApproveAchDepositRequestCreate() components.ForceApproveAchDepositRequestCreate {
	if o == nil {
		return components.ForceApproveAchDepositRequestCreate{}
	}
	return o.ForceApproveAchDepositRequestCreate
}

type AchDepositsForceApproveAchDepositResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AchDeposit *components.AchDeposit
	// INVALID_ARGUMENT: The request has an invalid argument.
	Status *components.Status
}

func (o *AchDepositsForceApproveAchDepositResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AchDepositsForceApproveAchDepositResponse) GetAchDeposit() *components.AchDeposit {
	if o == nil {
		return nil
	}
	return o.AchDeposit
}

func (o *AchDepositsForceApproveAchDepositResponse) GetStatus() *components.Status {
	if o == nil {
		return nil
	}
	return o.Status
}
