// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ascend-sdk/models/components"
)

type AchDepositsForceNocAchDepositRequest struct {
	// The account id.
	AccountID string `pathParam:"style=simple,explode=false,name=account_id"`
	// The achDeposit id.
	AchDepositID                    string                                     `pathParam:"style=simple,explode=false,name=achDeposit_id"`
	ForceNocAchDepositRequestCreate components.ForceNocAchDepositRequestCreate `request:"mediaType=application/json"`
}

func (o *AchDepositsForceNocAchDepositRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *AchDepositsForceNocAchDepositRequest) GetAchDepositID() string {
	if o == nil {
		return ""
	}
	return o.AchDepositID
}

func (o *AchDepositsForceNocAchDepositRequest) GetForceNocAchDepositRequestCreate() components.ForceNocAchDepositRequestCreate {
	if o == nil {
		return components.ForceNocAchDepositRequestCreate{}
	}
	return o.ForceNocAchDepositRequestCreate
}

type AchDepositsForceNocAchDepositResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AchDeposit *components.AchDeposit
	// INVALID_ARGUMENT: The request has an invalid argument.
	Status *components.Status
}

func (o *AchDepositsForceNocAchDepositResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AchDepositsForceNocAchDepositResponse) GetAchDeposit() *components.AchDeposit {
	if o == nil {
		return nil
	}
	return o.AchDeposit
}

func (o *AchDepositsForceNocAchDepositResponse) GetStatus() *components.Status {
	if o == nil {
		return nil
	}
	return o.Status
}
