// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ascend-sdk/models/components"
)

type AchDepositSchedulesGetAchDepositScheduleRequest struct {
	// The account id.
	AccountID string `pathParam:"style=simple,explode=false,name=account_id"`
	// The achDepositSchedule id.
	AchDepositScheduleID string `pathParam:"style=simple,explode=false,name=achDepositSchedule_id"`
}

func (o *AchDepositSchedulesGetAchDepositScheduleRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *AchDepositSchedulesGetAchDepositScheduleRequest) GetAchDepositScheduleID() string {
	if o == nil {
		return ""
	}
	return o.AchDepositScheduleID
}

type AchDepositSchedulesGetAchDepositScheduleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AchDepositSchedule *components.AchDepositSchedule
	// INVALID_ARGUMENT: The request has an invalid argument.
	Status *components.Status
}

func (o *AchDepositSchedulesGetAchDepositScheduleResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AchDepositSchedulesGetAchDepositScheduleResponse) GetAchDepositSchedule() *components.AchDepositSchedule {
	if o == nil {
		return nil
	}
	return o.AchDepositSchedule
}

func (o *AchDepositSchedulesGetAchDepositScheduleResponse) GetStatus() *components.Status {
	if o == nil {
		return nil
	}
	return o.Status
}
