// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/afs-public/ascend-sdk-go/models/components"
)

type AlternativeOrdersSettleAlternativeOrderRequest struct {
	// The account id.
	AccountID string `pathParam:"style=simple,explode=false,name=account_id"`
	// The alternativeOrder id.
	AlternativeOrderID                  string                                         `pathParam:"style=simple,explode=false,name=alternativeOrder_id"`
	SettleAlternativeOrderRequestCreate components.SettleAlternativeOrderRequestCreate `request:"mediaType=application/json"`
}

func (o *AlternativeOrdersSettleAlternativeOrderRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *AlternativeOrdersSettleAlternativeOrderRequest) GetAlternativeOrderID() string {
	if o == nil {
		return ""
	}
	return o.AlternativeOrderID
}

func (o *AlternativeOrdersSettleAlternativeOrderRequest) GetSettleAlternativeOrderRequestCreate() components.SettleAlternativeOrderRequestCreate {
	if o == nil {
		return components.SettleAlternativeOrderRequestCreate{}
	}
	return o.SettleAlternativeOrderRequestCreate
}

type AlternativeOrdersSettleAlternativeOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	AlternativeOrder *components.AlternativeOrder
	// INVALID_ARGUMENT: The request has an invalid argument.
	// FAILED_PRECONDITION: The requested resource is not in the expected state.
	Status *components.Status
}

func (o *AlternativeOrdersSettleAlternativeOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AlternativeOrdersSettleAlternativeOrderResponse) GetAlternativeOrder() *components.AlternativeOrder {
	if o == nil {
		return nil
	}
	return o.AlternativeOrder
}

func (o *AlternativeOrdersSettleAlternativeOrderResponse) GetStatus() *components.Status {
	if o == nil {
		return nil
	}
	return o.Status
}
