// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/afs-public/ascend-sdk-go/models/components"
)

type ExerciseServiceCreateOptionInstructionRequest struct {
	// The account id.
	AccountID string `pathParam:"style=simple,explode=false,name=account_id"`
	// The asset id.
	AssetID                 string                             `pathParam:"style=simple,explode=false,name=asset_id"`
	OptionInstructionCreate components.OptionInstructionCreate `request:"mediaType=application/json"`
}

func (o *ExerciseServiceCreateOptionInstructionRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *ExerciseServiceCreateOptionInstructionRequest) GetAssetID() string {
	if o == nil {
		return ""
	}
	return o.AssetID
}

func (o *ExerciseServiceCreateOptionInstructionRequest) GetOptionInstructionCreate() components.OptionInstructionCreate {
	if o == nil {
		return components.OptionInstructionCreate{}
	}
	return o.OptionInstructionCreate
}

type ExerciseServiceCreateOptionInstructionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	OptionInstruction *components.OptionInstruction
	// Default error response
	Status *components.Status
}

func (o *ExerciseServiceCreateOptionInstructionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ExerciseServiceCreateOptionInstructionResponse) GetOptionInstruction() *components.OptionInstruction {
	if o == nil {
		return nil
	}
	return o.OptionInstruction
}

func (o *ExerciseServiceCreateOptionInstructionResponse) GetStatus() *components.Status {
	if o == nil {
		return nil
	}
	return o.Status
}
