// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"ascend-sdk/models/components"
)

type InvestigationServiceGetInvestigationRequest struct {
	// The investigation id.
	InvestigationID string `pathParam:"style=simple,explode=false,name=investigation_id"`
}

func (o *InvestigationServiceGetInvestigationRequest) GetInvestigationID() string {
	if o == nil {
		return ""
	}
	return o.InvestigationID
}

type InvestigationServiceGetInvestigationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Investigation *components.Investigation
	// INVALID_ARGUMENT: The request is not valid, additional information may be present in the BadRequest details.
	Status *components.Status
}

func (o *InvestigationServiceGetInvestigationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *InvestigationServiceGetInvestigationResponse) GetInvestigation() *components.Investigation {
	if o == nil {
		return nil
	}
	return o.Investigation
}

func (o *InvestigationServiceGetInvestigationResponse) GetStatus() *components.Status {
	if o == nil {
		return nil
	}
	return o.Status
}
