// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/afs-public/ascend-sdk-go/models/components"
)

type OptionOrderServiceGetOptionOrderRequest struct {
	// The account id.
	AccountID string `pathParam:"style=simple,explode=false,name=account_id"`
	// The optionOrder id.
	OptionOrderID string `pathParam:"style=simple,explode=false,name=optionOrder_id"`
}

func (o *OptionOrderServiceGetOptionOrderRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *OptionOrderServiceGetOptionOrderRequest) GetOptionOrderID() string {
	if o == nil {
		return ""
	}
	return o.OptionOrderID
}

type OptionOrderServiceGetOptionOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	OptionOrder *components.OptionOrder
	// INVALID_ARGUMENT: The account_id or the option_order_id could not be determined for the request.
	Status *components.Status
}

func (o *OptionOrderServiceGetOptionOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OptionOrderServiceGetOptionOrderResponse) GetOptionOrder() *components.OptionOrder {
	if o == nil {
		return nil
	}
	return o.OptionOrder
}

func (o *OptionOrderServiceGetOptionOrderResponse) GetStatus() *components.Status {
	if o == nil {
		return nil
	}
	return o.Status
}
