// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	ascendsdkgo "github.com/afs-public/ascend-sdk-go"
	"github.com/afs-public/ascend-sdk-go/internal/utils"
	"github.com/afs-public/ascend-sdk-go/models/components"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestAlternativeInvestments_AlternativeInvestmentsListAlternativeInvestments(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("AlternativeInvestments_ListAlternativeInvestments")

	s := ascendsdkgo.New(
		ascendsdkgo.WithServerURL(utils.GetEnv("SERVICE_ACCOUNT_CREDS_URL", "")),
		ascendsdkgo.WithSecurity(components.Security{
			APIKey: ascendsdkgo.String(utils.GetEnv("API_KEY", "value")),
			ServiceAccountCreds: &components.ServiceAccountCreds{
				PrivateKey:   utils.GetEnv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
				Name:         utils.GetEnv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
				Organization: utils.GetEnv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
				Type:         utils.GetEnv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
			},
		}),
		ascendsdkgo.WithClient(testHTTPClient),
	)

	res, err := s.AlternativeInvestments.ListAlternativeInvestments(ctx, "-", ascendsdkgo.Int(25), ascendsdkgo.String(""), ascendsdkgo.String(""))
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestAlternativeInvestments_AlternativeInvestmentsGetAlternativeInvestment(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("AlternativeInvestments_GetAlternativeInvestment")

	s := ascendsdkgo.New(
		ascendsdkgo.WithServerURL(utils.GetEnv("SERVICE_ACCOUNT_CREDS_URL", "")),
		ascendsdkgo.WithSecurity(components.Security{
			APIKey: ascendsdkgo.String(utils.GetEnv("API_KEY", "value")),
			ServiceAccountCreds: &components.ServiceAccountCreds{
				PrivateKey:   utils.GetEnv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
				Name:         utils.GetEnv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
				Organization: utils.GetEnv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
				Type:         utils.GetEnv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
			},
		}),
		ascendsdkgo.WithClient(testHTTPClient),
	)

	res, err := s.AlternativeInvestments.GetAlternativeInvestment(ctx, "5953715")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}
