// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package tests

import (
	"context"
	ascendsdkgo "github.com/afs-public/ascend-sdk-go"
	"github.com/afs-public/ascend-sdk-go/internal/utils"
	"github.com/afs-public/ascend-sdk-go/models/components"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func TestAlternativeInvestmentDocuments_AlternativeInvestmentDocumentsListAlternativeInvestmentDocuments(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("AlternativeInvestmentDocuments_ListAlternativeInvestmentDocuments")

	s := ascendsdkgo.New(
		ascendsdkgo.WithServerURL(utils.GetEnv("SERVICE_ACCOUNT_CREDS_URL", "")),
		ascendsdkgo.WithSecurity(components.Security{
			APIKey: ascendsdkgo.String(utils.GetEnv("API_KEY", "value")),
			ServiceAccountCreds: &components.ServiceAccountCreds{
				PrivateKey:   utils.GetEnv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
				Name:         utils.GetEnv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
				Organization: utils.GetEnv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
				Type:         utils.GetEnv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
			},
		}),
		ascendsdkgo.WithClient(testHTTPClient),
	)

	res, err := s.AlternativeInvestmentDocuments.ListAlternativeInvestmentDocuments(ctx, "5953715", ascendsdkgo.Int(25), ascendsdkgo.String(""), ascendsdkgo.String(""))
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestAlternativeInvestmentDocuments_AlternativeInvestmentDocumentsGetAlternativeInvestmentDocument(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("AlternativeInvestmentDocuments_GetAlternativeInvestmentDocument")

	s := ascendsdkgo.New(
		ascendsdkgo.WithServerURL(utils.GetEnv("SERVICE_ACCOUNT_CREDS_URL", "")),
		ascendsdkgo.WithSecurity(components.Security{
			APIKey: ascendsdkgo.String(utils.GetEnv("API_KEY", "value")),
			ServiceAccountCreds: &components.ServiceAccountCreds{
				PrivateKey:   utils.GetEnv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
				Name:         utils.GetEnv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
				Organization: utils.GetEnv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
				Type:         utils.GetEnv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
			},
		}),
		ascendsdkgo.WithClient(testHTTPClient),
	)

	res, err := s.AlternativeInvestmentDocuments.GetAlternativeInvestmentDocument(ctx, "5953715", "01K98MKTGBDXF9XXVQH5RKPMMA")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}

func TestAlternativeInvestmentDocuments_AlternativeInvestmentDocumentsDownloadAlternativeInvestmentDocument(t *testing.T) {
	ctx := context.Background()

	testHTTPClient := createTestHTTPClient("AlternativeInvestmentDocuments_DownloadAlternativeInvestmentDocument")

	s := ascendsdkgo.New(
		ascendsdkgo.WithServerURL(utils.GetEnv("SERVICE_ACCOUNT_CREDS_URL", "")),
		ascendsdkgo.WithSecurity(components.Security{
			APIKey: ascendsdkgo.String(utils.GetEnv("API_KEY", "value")),
			ServiceAccountCreds: &components.ServiceAccountCreds{
				PrivateKey:   utils.GetEnv("SERVICE_ACCOUNT_CREDS_PRIVATE_KEY", "value"),
				Name:         utils.GetEnv("SERVICE_ACCOUNT_CREDS_NAME", "value"),
				Organization: utils.GetEnv("SERVICE_ACCOUNT_CREDS_ORGANIZATION", "value"),
				Type:         utils.GetEnv("SERVICE_ACCOUNT_CREDS_TYPE", "value"),
			},
		}),
		ascendsdkgo.WithClient(testHTTPClient),
	)

	res, err := s.AlternativeInvestmentDocuments.DownloadAlternativeInvestmentDocument(ctx, "5953715", "01K98MKTGBDXF9XXVQH5RKPMMA")
	require.NoError(t, err)
	assert.Equal(t, 200, res.HTTPMeta.Response.StatusCode)

}
