// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AddOrdersRequestCreate - The message to add a list of basket orders to a basket
type AddOrdersRequestCreate struct {
	// The orders to add to the basket. A maximum of 1000 orders can be added to a basket at a time.
	BasketOrders []BasketOrderCreate `json:"basket_orders"`
	// Format: correspondents/{correspondent}/baskets/{basket}
	Name string `json:"name"`
}

func (o *AddOrdersRequestCreate) GetBasketOrders() []BasketOrderCreate {
	if o == nil {
		return []BasketOrderCreate{}
	}
	return o.BasketOrders
}

func (o *AddOrdersRequestCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
