// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/afs-public/ascend-sdk-go/internal/utils"
)

// BasketOrderCreateAssetType - The type of the asset in this order
type BasketOrderCreateAssetType string

const (
	BasketOrderCreateAssetTypeAssetTypeUnspecified BasketOrderCreateAssetType = "ASSET_TYPE_UNSPECIFIED"
	BasketOrderCreateAssetTypeEquity               BasketOrderCreateAssetType = "EQUITY"
)

func (e BasketOrderCreateAssetType) ToPointer() *BasketOrderCreateAssetType {
	return &e
}
func (e *BasketOrderCreateAssetType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ASSET_TYPE_UNSPECIFIED":
		fallthrough
	case "EQUITY":
		*e = BasketOrderCreateAssetType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BasketOrderCreateAssetType: %v", v)
	}
}

// BasketOrderCreateIdentifierType - The identifier type of the asset being ordered. For Equities: only SYMBOL is supported
type BasketOrderCreateIdentifierType string

const (
	BasketOrderCreateIdentifierTypeSymbol BasketOrderCreateIdentifierType = "SYMBOL"
	BasketOrderCreateIdentifierTypeCusip  BasketOrderCreateIdentifierType = "CUSIP"
	BasketOrderCreateIdentifierTypeIsin   BasketOrderCreateIdentifierType = "ISIN"
)

func (e BasketOrderCreateIdentifierType) ToPointer() *BasketOrderCreateIdentifierType {
	return &e
}
func (e *BasketOrderCreateIdentifierType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SYMBOL":
		fallthrough
	case "CUSIP":
		fallthrough
	case "ISIN":
		*e = BasketOrderCreateIdentifierType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BasketOrderCreateIdentifierType: %v", v)
	}
}

// BasketOrderCreateOrderType - The execution type of this order.
type BasketOrderCreateOrderType string

const (
	BasketOrderCreateOrderTypeOrderTypeUnspecified BasketOrderCreateOrderType = "ORDER_TYPE_UNSPECIFIED"
	BasketOrderCreateOrderTypeMarket               BasketOrderCreateOrderType = "MARKET"
)

func (e BasketOrderCreateOrderType) ToPointer() *BasketOrderCreateOrderType {
	return &e
}
func (e *BasketOrderCreateOrderType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ORDER_TYPE_UNSPECIFIED":
		fallthrough
	case "MARKET":
		*e = BasketOrderCreateOrderType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BasketOrderCreateOrderType: %v", v)
	}
}

// BasketOrderCreateSide - The side of this order.
type BasketOrderCreateSide string

const (
	BasketOrderCreateSideSideUnspecified BasketOrderCreateSide = "SIDE_UNSPECIFIED"
	BasketOrderCreateSideBuy             BasketOrderCreateSide = "BUY"
	BasketOrderCreateSideSell            BasketOrderCreateSide = "SELL"
)

func (e BasketOrderCreateSide) ToPointer() *BasketOrderCreateSide {
	return &e
}
func (e *BasketOrderCreateSide) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SIDE_UNSPECIFIED":
		fallthrough
	case "BUY":
		fallthrough
	case "SELL":
		*e = BasketOrderCreateSide(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BasketOrderCreateSide: %v", v)
	}
}

// BasketOrderCreateTimeInForce - Must be the value "DAY". Regulatory requirements dictate that the system capture the intended time_in_force, which is why this a mandatory field.
type BasketOrderCreateTimeInForce string

const (
	BasketOrderCreateTimeInForceTimeInForceUnspecified BasketOrderCreateTimeInForce = "TIME_IN_FORCE_UNSPECIFIED"
	BasketOrderCreateTimeInForceDay                    BasketOrderCreateTimeInForce = "DAY"
)

func (e BasketOrderCreateTimeInForce) ToPointer() *BasketOrderCreateTimeInForce {
	return &e
}
func (e *BasketOrderCreateTimeInForce) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TIME_IN_FORCE_UNSPECIFIED":
		fallthrough
	case "DAY":
		*e = BasketOrderCreateTimeInForce(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BasketOrderCreateTimeInForce: %v", v)
	}
}

// BasketOrderCreate - The message describing an order that has been added to a basket
type BasketOrderCreate struct {
	// The identifier of the account transacting this order
	AccountID string `json:"account_id"`
	// The type of the asset in this order
	AssetType BasketOrderCreateAssetType `json:"asset_type"`
	// User-supplied unique order ID. Cannot be more than 40 characters long.
	ClientOrderID string `json:"client_order_id"`
	// Time the order request was received by the client
	ClientOrderReceivedTime *time.Time `json:"client_order_received_time,omitempty"`
	// Identifier of the asset (of the type specified in `identifier_type`).
	Identifier string `json:"identifier"`
	// The identifier type of the asset being ordered. For Equities: only SYMBOL is supported
	IdentifierType BasketOrderCreateIdentifierType `json:"identifier_type"`
	// The execution type of this order.
	OrderType BasketOrderCreateOrderType `json:"order_type"`
	// A representation of a decimal value, such as 2.5. Clients may convert values into language-native decimal formats, such as Java's [BigDecimal][] or Python's [decimal.Decimal][].
	//
	//  [BigDecimal]:
	//  https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/math/BigDecimal.html
	//  [decimal.Decimal]: https://docs.python.org/3/library/decimal.html
	Quantity *DecimalCreate `json:"quantity,omitempty"`
	// The side of this order.
	Side BasketOrderCreateSide `json:"side"`
	// Must be the value "DAY". Regulatory requirements dictate that the system capture the intended time_in_force, which is why this a mandatory field.
	TimeInForce BasketOrderCreateTimeInForce `json:"time_in_force"`
}

func (b BasketOrderCreate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BasketOrderCreate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BasketOrderCreate) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *BasketOrderCreate) GetAssetType() BasketOrderCreateAssetType {
	if o == nil {
		return BasketOrderCreateAssetType("")
	}
	return o.AssetType
}

func (o *BasketOrderCreate) GetClientOrderID() string {
	if o == nil {
		return ""
	}
	return o.ClientOrderID
}

func (o *BasketOrderCreate) GetClientOrderReceivedTime() *time.Time {
	if o == nil {
		return nil
	}
	return o.ClientOrderReceivedTime
}

func (o *BasketOrderCreate) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *BasketOrderCreate) GetIdentifierType() BasketOrderCreateIdentifierType {
	if o == nil {
		return BasketOrderCreateIdentifierType("")
	}
	return o.IdentifierType
}

func (o *BasketOrderCreate) GetOrderType() BasketOrderCreateOrderType {
	if o == nil {
		return BasketOrderCreateOrderType("")
	}
	return o.OrderType
}

func (o *BasketOrderCreate) GetQuantity() *DecimalCreate {
	if o == nil {
		return nil
	}
	return o.Quantity
}

func (o *BasketOrderCreate) GetSide() BasketOrderCreateSide {
	if o == nil {
		return BasketOrderCreateSide("")
	}
	return o.Side
}

func (o *BasketOrderCreate) GetTimeInForce() BasketOrderCreateTimeInForce {
	if o == nil {
		return BasketOrderCreateTimeInForce("")
	}
	return o.TimeInForce
}
