// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CancelOptionOrderRequestCreate - The message to request cancellation of an existing option order
type CancelOptionOrderRequestCreate struct {
	// Format: accounts/{account_id}/optionOrders/{option_order_id}
	Name string `json:"name"`
}

func (o *CancelOptionOrderRequestCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
