// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CancelCreditRequestCreate - Request to cancel an existing credit
type CancelCreditRequestCreate struct {
	// The name of the credit to cancel
	Name string `json:"name"`
	// The optional reason about why the credit is being canceled
	Reason *string `json:"reason,omitempty"`
}

func (o *CancelCreditRequestCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CancelCreditRequestCreate) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}
