// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CancelAchDepositScheduleRequestCreate - Request to cancel an ACH deposit transfer schedule
type CancelAchDepositScheduleRequestCreate struct {
	// A comment as to why the ACH deposit schedule is being canceled
	Comment *string `json:"comment,omitempty"`
	// The name of the ACH deposit transfer schedule to cancel
	Name string `json:"name"`
}

func (o *CancelAchDepositScheduleRequestCreate) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}

func (o *CancelAchDepositScheduleRequestCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
