// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DeliveryMethod - The Delivery method of check withdrawal
type DeliveryMethod string

const (
	DeliveryMethodDeliveryMethodUnspecified DeliveryMethod = "DELIVERY_METHOD_UNSPECIFIED"
	DeliveryMethodStandard                  DeliveryMethod = "STANDARD"
	DeliveryMethodOvernight                 DeliveryMethod = "OVERNIGHT"
	DeliveryMethodOvernightToApex           DeliveryMethod = "OVERNIGHT_TO_APEX"
)

func (e DeliveryMethod) ToPointer() *DeliveryMethod {
	return &e
}

// CheckWithdrawalScheduleCreate - A withdrawal transfer schedule using the Check mechanism
type CheckWithdrawalScheduleCreate struct {
	// A Check Beneficiary
	Beneficiary *TransfersBeneficiaryCreate `json:"beneficiary,omitempty"`
	// The Delivery method of check withdrawal
	DeliveryMethod DeliveryMethod `json:"delivery_method"`
	// Memos on the check. The max number of lines is 3, with max of 30 characters per line
	Memos []string `json:"memos,omitempty"`
	// A distribution from a retirement account.
	RetirementDistribution *RetirementDistributionCreate `json:"retirement_distribution,omitempty"`
	// Details of withdrawal schedule transfers
	ScheduleDetails WithdrawalScheduleDetailsCreate `json:"schedule_details"`
}

func (o *CheckWithdrawalScheduleCreate) GetBeneficiary() *TransfersBeneficiaryCreate {
	if o == nil {
		return nil
	}
	return o.Beneficiary
}

func (o *CheckWithdrawalScheduleCreate) GetDeliveryMethod() DeliveryMethod {
	if o == nil {
		return DeliveryMethod("")
	}
	return o.DeliveryMethod
}

func (o *CheckWithdrawalScheduleCreate) GetMemos() []string {
	if o == nil {
		return nil
	}
	return o.Memos
}

func (o *CheckWithdrawalScheduleCreate) GetRetirementDistribution() *RetirementDistributionCreate {
	if o == nil {
		return nil
	}
	return o.RetirementDistribution
}

func (o *CheckWithdrawalScheduleCreate) GetScheduleDetails() WithdrawalScheduleDetailsCreate {
	if o == nil {
		return WithdrawalScheduleDetailsCreate{}
	}
	return o.ScheduleDetails
}
