// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RegularAmount - Summed contribution amounts throughout the year
type RegularAmount struct {
	// The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details
	Value *string `json:"value,omitempty"`
}

func (o *RegularAmount) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

// RolloverAmount - Rollover contribution amount
type RolloverAmount struct {
	// The decimal value, as a string; Refer to [Google’s Decimal type protocol buffer](https://github.com/googleapis/googleapis/blob/40203ca1880849480bbff7b8715491060bbccdf1/google/type/decimal.proto#L33) for details
	Value *string `json:"value,omitempty"`
}

func (o *RolloverAmount) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}

// ContributionSummary - Regular and rollover contribution amounts for one tax year
type ContributionSummary struct {
	// Retirement account id these contribution amounts are for
	Name *string `json:"name,omitempty"`
	// Summed contribution amounts throughout the year
	RegularAmount *RegularAmount `json:"regular_amount,omitempty"`
	// Rollover contribution amount
	RolloverAmount *RolloverAmount `json:"rollover_amount,omitempty"`
	// Tax year these contribution amounts are for
	TaxYear *int `json:"tax_year,omitempty"`
}

func (o *ContributionSummary) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *ContributionSummary) GetRegularAmount() *RegularAmount {
	if o == nil {
		return nil
	}
	return o.RegularAmount
}

func (o *ContributionSummary) GetRolloverAmount() *RolloverAmount {
	if o == nil {
		return nil
	}
	return o.RolloverAmount
}

func (o *ContributionSummary) GetTaxYear() *int {
	if o == nil {
		return nil
	}
	return o.TaxYear
}
