// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CheckTypes string

const (
	CheckTypesCheckTypeUnspecified CheckTypes = "CHECK_TYPE_UNSPECIFIED"
	CheckTypesDatabase             CheckTypes = "DATABASE"
	CheckTypesDocumentary          CheckTypes = "DOCUMENTARY"
)

func (e CheckTypes) ToPointer() *CheckTypes {
	return &e
}

// CustomerIdentification includes the details of a customer identification check
type CustomerIdentification struct {
	// The types of checks being requested
	CheckTypes []CheckTypes `json:"check_types,omitempty"`
	// required format: correspondents/{correspondent_id}/customerIdentifications/{customer_identification_id}
	Name *string `json:"name,omitempty"`
	// The results of the identity verification check(s)
	Results []CustomerIdentificationResult `json:"results,omitempty"`
}

func (o *CustomerIdentification) GetCheckTypes() []CheckTypes {
	if o == nil {
		return nil
	}
	return o.CheckTypes
}

func (o *CustomerIdentification) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CustomerIdentification) GetResults() []CustomerIdentificationResult {
	if o == nil {
		return nil
	}
	return o.Results
}
