// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// DeviceType - The type of device (e.g., mobile, desktop, tablet)
type DeviceType string

const (
	DeviceTypeDeviceTypeUnspecified DeviceType = "DEVICE_TYPE_UNSPECIFIED"
	DeviceTypeDesktop               DeviceType = "DESKTOP"
	DeviceTypeMobile                DeviceType = "MOBILE"
	DeviceTypeTablet                DeviceType = "TABLET"
)

func (e DeviceType) ToPointer() *DeviceType {
	return &e
}

// GeolocationMechanism - Method used to determine the end-user's device geolocation
type GeolocationMechanism string

const (
	GeolocationMechanismGeolocationMechanismUnspecified GeolocationMechanism = "GEOLOCATION_MECHANISM_UNSPECIFIED"
	GeolocationMechanismDeviceGps                       GeolocationMechanism = "DEVICE_GPS"
	GeolocationMechanismIPLookup                        GeolocationMechanism = "IP_LOOKUP"
)

func (e GeolocationMechanism) ToPointer() *GeolocationMechanism {
	return &e
}

// DeviceMetadataCreate - End-user device metadata for fraud detection and compliance All fields must represent the actual end-user's device, not any intermediate proxy or client server through which requests may be routed
type DeviceMetadataCreate struct {
	// Unique identifier for the device
	DeviceID *string `json:"device_id,omitempty"`
	// The type of device (e.g., mobile, desktop, tablet)
	DeviceType *DeviceType `json:"device_type,omitempty"`
	// An object that represents a latitude/longitude pair. This is expressed as a pair of doubles to represent degrees latitude and degrees longitude. Unless specified otherwise, this must conform to the <a href="http://www.unoosa.org/pdf/icg/2012/template/WGS_84.pdf">WGS84 standard</a>. Values must be within normalized ranges.
	Geolocation *LatLngCreate `json:"geolocation,omitempty"`
	// Method used to determine the end-user's device geolocation
	GeolocationMechanism *GeolocationMechanism `json:"geolocation_mechanism,omitempty"`
	// The IP address of the end-user's device This must be the actual end-user's IP address, not the IP of any proxy or client server Must be a valid IPv4 or IPv6 address format IPv4 examples: "203.0.113.42", "198.51.100.1", "8.8.8.8" IPv6 examples: "2001:0db8:85a3::8a2e:0370:7334", "2606:4700:4700::1111"
	IPAddress string `json:"ip_address"`
	// The user agent string from the end-user's device browser or application
	UserAgent *string `json:"user_agent,omitempty"`
}

func (o *DeviceMetadataCreate) GetDeviceID() *string {
	if o == nil {
		return nil
	}
	return o.DeviceID
}

func (o *DeviceMetadataCreate) GetDeviceType() *DeviceType {
	if o == nil {
		return nil
	}
	return o.DeviceType
}

func (o *DeviceMetadataCreate) GetGeolocation() *LatLngCreate {
	if o == nil {
		return nil
	}
	return o.Geolocation
}

func (o *DeviceMetadataCreate) GetGeolocationMechanism() *GeolocationMechanism {
	if o == nil {
		return nil
	}
	return o.GeolocationMechanism
}

func (o *DeviceMetadataCreate) GetIPAddress() string {
	if o == nil {
		return ""
	}
	return o.IPAddress
}

func (o *DeviceMetadataCreate) GetUserAgent() *string {
	if o == nil {
		return nil
	}
	return o.UserAgent
}
