// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ForceRejectIctDepositRequestCreate - Request to simulate the rejection of an ICT deposit
type ForceRejectIctDepositRequestCreate struct {
	// Full name of the ICT deposit resource to force a rejection on. Contains account id and ICT deposit id.
	Name string `json:"name"`
}

func (o *ForceRejectIctDepositRequestCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
