// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan - Option to auto-enroll in Dividend Reinvestment; defaults to DIVIDEND_REINVESTMENT_ENROLL
type ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan string

const (
	ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlanAutoEnrollDividendReinvestmentUnspecified ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan = "AUTO_ENROLL_DIVIDEND_REINVESTMENT_UNSPECIFIED"
	ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlanDividendReinvestmentEnroll                ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan = "DIVIDEND_REINVESTMENT_ENROLL"
	ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlanDividendReinvestmentDecline               ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan = "DIVIDEND_REINVESTMENT_DECLINE"
)

func (e ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan) ToPointer() *ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan {
	return &e
}

// ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep - Option to auto-enroll in FDIC cash sweep; defaults to FDIC_CASH_SWEEP_ENROLL
type ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep string

const (
	ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweepAutoEnrollFdicCashSweepUnspecified ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep = "AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED"
	ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweepFdicCashSweepEnroll                ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep = "FDIC_CASH_SWEEP_ENROLL"
	ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweepFdicCashSweepDecline               ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep = "FDIC_CASH_SWEEP_DECLINE"
)

func (e ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep) ToPointer() *ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep {
	return &e
}

type ForeignIndividualAccountEnrollmentMetadataCreate struct {
	// Option to auto-enroll in Dividend Reinvestment; defaults to DIVIDEND_REINVESTMENT_ENROLL
	DividendReinvestmentPlan *ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan `json:"dividend_reinvestment_plan,omitempty"`
	// Option to auto-enroll in FDIC cash sweep; defaults to FDIC_CASH_SWEEP_ENROLL
	FdicCashSweep *ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep `json:"fdic_cash_sweep,omitempty"`
	// Enrollment metadata for Accounts that have a foreign Legal Natural Person owner.
	ForeignNaturalPersonAccountEnrollmentMetadata ForeignNaturalPersonAccountEnrollmentMetadataCreate `json:"foreign_natural_person_account_enrollment_metadata"`
}

func (o *ForeignIndividualAccountEnrollmentMetadataCreate) GetDividendReinvestmentPlan() *ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan {
	if o == nil {
		return nil
	}
	return o.DividendReinvestmentPlan
}

func (o *ForeignIndividualAccountEnrollmentMetadataCreate) GetFdicCashSweep() *ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep {
	if o == nil {
		return nil
	}
	return o.FdicCashSweep
}

func (o *ForeignIndividualAccountEnrollmentMetadataCreate) GetForeignNaturalPersonAccountEnrollmentMetadata() ForeignNaturalPersonAccountEnrollmentMetadataCreate {
	if o == nil {
		return ForeignNaturalPersonAccountEnrollmentMetadataCreate{}
	}
	return o.ForeignNaturalPersonAccountEnrollmentMetadata
}
