// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan - Option to auto-enroll in Dividend Reinvestment; defaults to true
type ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan string

const (
	ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlanAutoEnrollDividendReinvestmentUnspecified ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan = "AUTO_ENROLL_DIVIDEND_REINVESTMENT_UNSPECIFIED"
	ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlanDividendReinvestmentEnroll                ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan = "DIVIDEND_REINVESTMENT_ENROLL"
	ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlanDividendReinvestmentDecline               ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan = "DIVIDEND_REINVESTMENT_DECLINE"
)

func (e ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan) ToPointer() *ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan {
	return &e
}
func (e *ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AUTO_ENROLL_DIVIDEND_REINVESTMENT_UNSPECIFIED":
		fallthrough
	case "DIVIDEND_REINVESTMENT_ENROLL":
		fallthrough
	case "DIVIDEND_REINVESTMENT_DECLINE":
		*e = ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan: %v", v)
	}
}

// ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep - Option to auto-enroll in FDIC cash sweep; defaults to true
type ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep string

const (
	ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweepAutoEnrollFdicCashSweepUnspecified ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep = "AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED"
	ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweepFdicCashSweepEnroll                ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep = "FDIC_CASH_SWEEP_ENROLL"
	ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweepFdicCashSweepDecline               ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep = "FDIC_CASH_SWEEP_DECLINE"
)

func (e ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep) ToPointer() *ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep {
	return &e
}
func (e *ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED":
		fallthrough
	case "FDIC_CASH_SWEEP_ENROLL":
		fallthrough
	case "FDIC_CASH_SWEEP_DECLINE":
		*e = ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep: %v", v)
	}
}

type ForeignIndividualAccountEnrollmentMetadataCreate struct {
	// Option to auto-enroll in Dividend Reinvestment; defaults to true
	DividendReinvestmentPlan *ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan `json:"dividend_reinvestment_plan,omitempty"`
	// Option to auto-enroll in FDIC cash sweep; defaults to true
	FdicCashSweep *ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep `json:"fdic_cash_sweep,omitempty"`
	// Enrollment metadata for Accounts that have a foreign Legal Natural Person owner.
	ForeignNaturalPersonAccountEnrollmentMetadata ForeignNaturalPersonAccountEnrollmentMetadataCreate `json:"foreign_natural_person_account_enrollment_metadata"`
}

func (o *ForeignIndividualAccountEnrollmentMetadataCreate) GetDividendReinvestmentPlan() *ForeignIndividualAccountEnrollmentMetadataCreateDividendReinvestmentPlan {
	if o == nil {
		return nil
	}
	return o.DividendReinvestmentPlan
}

func (o *ForeignIndividualAccountEnrollmentMetadataCreate) GetFdicCashSweep() *ForeignIndividualAccountEnrollmentMetadataCreateFdicCashSweep {
	if o == nil {
		return nil
	}
	return o.FdicCashSweep
}

func (o *ForeignIndividualAccountEnrollmentMetadataCreate) GetForeignNaturalPersonAccountEnrollmentMetadata() ForeignNaturalPersonAccountEnrollmentMetadataCreate {
	if o == nil {
		return ForeignNaturalPersonAccountEnrollmentMetadataCreate{}
	}
	return o.ForeignNaturalPersonAccountEnrollmentMetadata
}
