// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FuturesInvestmentObjective - The primary investment objective for the futures account
type FuturesInvestmentObjective string

const (
	FuturesInvestmentObjectiveFuturesInvestmentObjectiveUnspecified FuturesInvestmentObjective = "FUTURES_INVESTMENT_OBJECTIVE_UNSPECIFIED"
	FuturesInvestmentObjectiveSpeculation                           FuturesInvestmentObjective = "SPECULATION"
	FuturesInvestmentObjectiveHedging                               FuturesInvestmentObjective = "HEDGING"
)

func (e FuturesInvestmentObjective) ToPointer() *FuturesInvestmentObjective {
	return &e
}

// FuturesEnrollmentMetadataCreate - Enrollment metadata for the FUTURES enrollment type
type FuturesEnrollmentMetadataCreate struct {
	// Indicates whether the account is registered with the CFTC NFA
	CtfcNfaRegistered bool `json:"ctfc_nfa_registered"`
	// Indicates whether the account owner is a member of any exchanges
	ExchangeMember bool `json:"exchange_member"`
	// Indicates whether the futures account is owned or controlled by a FCM
	FcmOwnedOrControlled bool `json:"fcm_owned_or_controlled"`
	// Indicates whether the funds in the futures account are owned by the account owner
	FundsOwnedByAccountOwner bool `json:"funds_owned_by_account_owner"`
	// Indicates whether the account owner has prior experience trading futures
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	FuturesExperience *bool `json:"futures_experience,omitempty"`
	// The primary investment objective for the futures account
	FuturesInvestmentObjective FuturesInvestmentObjective `json:"futures_investment_objective"`
	// Indicates whether the account will trade investment retired funds
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	InvestmentRetiredFunds *bool `json:"investment_retired_funds,omitempty"`
	// Indicates whether the account owner has experience with various trading options and strategies
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	OptionsExperience *bool `json:"options_experience,omitempty"`
	// Indicates whether the account owner understands the risks associated with trading futures
	UnderstandFuturesRisks bool `json:"understand_futures_risks"`
	// Indicates whether the account owner understands that losses can exceed deposited funds
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	UnderstandLossBeyondFunds *bool `json:"understand_loss_beyond_funds,omitempty"`
}

func (o *FuturesEnrollmentMetadataCreate) GetCtfcNfaRegistered() bool {
	if o == nil {
		return false
	}
	return o.CtfcNfaRegistered
}

func (o *FuturesEnrollmentMetadataCreate) GetExchangeMember() bool {
	if o == nil {
		return false
	}
	return o.ExchangeMember
}

func (o *FuturesEnrollmentMetadataCreate) GetFcmOwnedOrControlled() bool {
	if o == nil {
		return false
	}
	return o.FcmOwnedOrControlled
}

func (o *FuturesEnrollmentMetadataCreate) GetFundsOwnedByAccountOwner() bool {
	if o == nil {
		return false
	}
	return o.FundsOwnedByAccountOwner
}

func (o *FuturesEnrollmentMetadataCreate) GetFuturesExperience() *bool {
	if o == nil {
		return nil
	}
	return o.FuturesExperience
}

func (o *FuturesEnrollmentMetadataCreate) GetFuturesInvestmentObjective() FuturesInvestmentObjective {
	if o == nil {
		return FuturesInvestmentObjective("")
	}
	return o.FuturesInvestmentObjective
}

func (o *FuturesEnrollmentMetadataCreate) GetInvestmentRetiredFunds() *bool {
	if o == nil {
		return nil
	}
	return o.InvestmentRetiredFunds
}

func (o *FuturesEnrollmentMetadataCreate) GetOptionsExperience() *bool {
	if o == nil {
		return nil
	}
	return o.OptionsExperience
}

func (o *FuturesEnrollmentMetadataCreate) GetUnderstandFuturesRisks() bool {
	if o == nil {
		return false
	}
	return o.UnderstandFuturesRisks
}

func (o *FuturesEnrollmentMetadataCreate) GetUnderstandLossBeyondFunds() *bool {
	if o == nil {
		return nil
	}
	return o.UnderstandLossBeyondFunds
}
