// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlan - Option to auto-enroll in Dividend Reinvestment; defaults to DIVIDEND_REINVESTMENT_ENROLL
type JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlan string

const (
	JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlanAutoEnrollDividendReinvestmentUnspecified JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlan = "AUTO_ENROLL_DIVIDEND_REINVESTMENT_UNSPECIFIED"
	JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlanDividendReinvestmentEnroll                JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlan = "DIVIDEND_REINVESTMENT_ENROLL"
	JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlanDividendReinvestmentDecline               JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlan = "DIVIDEND_REINVESTMENT_DECLINE"
)

func (e JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlan) ToPointer() *JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlan {
	return &e
}

// JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweep - Option to auto-enroll in FDIC cash sweep; defaults to FDIC_CASH_SWEEP_ENROLL
type JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweep string

const (
	JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweepAutoEnrollFdicCashSweepUnspecified JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweep = "AUTO_ENROLL_FDIC_CASH_SWEEP_UNSPECIFIED"
	JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweepFdicCashSweepEnroll                JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweep = "FDIC_CASH_SWEEP_ENROLL"
	JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweepFdicCashSweepDecline               JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweep = "FDIC_CASH_SWEEP_DECLINE"
)

func (e JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweep) ToPointer() *JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweep {
	return &e
}

// JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple - The legal residency state of a married couple
type JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple string

const (
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleLegalResidencyStateOfMarriedCoupleUnspecified JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "LEGAL_RESIDENCY_STATE_OF_MARRIED_COUPLE_UNSPECIFIED"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleAk                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "AK"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleAz                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "AZ"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleAr                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "AR"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleCa                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "CA"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleDe                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "DE"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleFl                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "FL"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleHi                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "HI"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleID                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "ID"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleIl                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "IL"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleIn                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "IN"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleKy                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "KY"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleLa                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "LA"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleMd                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "MD"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleMa                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "MA"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleMi                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "MI"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleMs                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "MS"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleMo                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "MO"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleNv                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "NV"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleNj                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "NJ"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleNm                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "NM"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleNy                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "NY"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleNc                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "NC"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleOh                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "OH"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleOk                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "OK"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleOr                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "OR"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouplePa                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "PA"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleRi                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "RI"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleTn                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "TN"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleTx                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "TX"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleVt                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "VT"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleVa                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "VA"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleWa                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "WA"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleWi                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "WI"
	JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCoupleWy                                            JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple = "WY"
)

func (e JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple) ToPointer() *JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple {
	return &e
}

// JointTenantsByEntiretyEnrollmentMetadataCreate - Enrollment metadata for the Joint Tenants by Entirety Registration enrollment type
type JointTenantsByEntiretyEnrollmentMetadataCreate struct {
	// Option to auto-enroll in Dividend Reinvestment; defaults to DIVIDEND_REINVESTMENT_ENROLL
	DividendReinvestmentPlan *JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlan `json:"dividend_reinvestment_plan,omitempty"`
	// Option to auto-enroll in FDIC cash sweep; defaults to FDIC_CASH_SWEEP_ENROLL
	FdicCashSweep *JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweep `json:"fdic_cash_sweep,omitempty"`
	// The legal residency state of a married couple
	LegalResidencyStateOfMarriedCouple JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple `json:"legal_residency_state_of_married_couple"`
}

func (o *JointTenantsByEntiretyEnrollmentMetadataCreate) GetDividendReinvestmentPlan() *JointTenantsByEntiretyEnrollmentMetadataCreateDividendReinvestmentPlan {
	if o == nil {
		return nil
	}
	return o.DividendReinvestmentPlan
}

func (o *JointTenantsByEntiretyEnrollmentMetadataCreate) GetFdicCashSweep() *JointTenantsByEntiretyEnrollmentMetadataCreateFdicCashSweep {
	if o == nil {
		return nil
	}
	return o.FdicCashSweep
}

func (o *JointTenantsByEntiretyEnrollmentMetadataCreate) GetLegalResidencyStateOfMarriedCouple() JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple {
	if o == nil {
		return JointTenantsByEntiretyEnrollmentMetadataCreateLegalResidencyStateOfMarriedCouple("")
	}
	return o.LegalResidencyStateOfMarriedCouple
}
