// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RebookTradeAllocationRequestCreate - Used to correct a trade allocation.
type RebookTradeAllocationRequestCreate struct {
	// The name of the original trade allocation to rebook.
	Name string `json:"name"`
	// A globally unique UUID that is specific to the request. This id is used to prevent duplicate requests from being processed.
	RequestID string `json:"request_id"`
	// A TradeAllocation represents the movement of positions between two ascend accounts.
	TradeAllocation TradeAllocationCreate `json:"trade_allocation"`
}

func (o *RebookTradeAllocationRequestCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *RebookTradeAllocationRequestCreate) GetRequestID() string {
	if o == nil {
		return ""
	}
	return o.RequestID
}

func (o *RebookTradeAllocationRequestCreate) GetTradeAllocation() TradeAllocationCreate {
	if o == nil {
		return TradeAllocationCreate{}
	}
	return o.TradeAllocation
}
