// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SearchOpenLotsRequestCreateIdentifierType - The type of the identifier provided in the identifier field. Please include an identifier_type if you are using an identifier. (-- api-linter: core::0140::abbreviations=disabled   aip.dev/not-precedent: Aligning with apex api standard for identifiers)
type SearchOpenLotsRequestCreateIdentifierType string

const (
	SearchOpenLotsRequestCreateIdentifierTypeIdentifierTypeUnspecified SearchOpenLotsRequestCreateIdentifierType = "IDENTIFIER_TYPE_UNSPECIFIED"
	SearchOpenLotsRequestCreateIdentifierTypeAssetID                   SearchOpenLotsRequestCreateIdentifierType = "ASSET_ID"
	SearchOpenLotsRequestCreateIdentifierTypeSymbol                    SearchOpenLotsRequestCreateIdentifierType = "SYMBOL"
	SearchOpenLotsRequestCreateIdentifierTypeCusip                     SearchOpenLotsRequestCreateIdentifierType = "CUSIP"
)

func (e SearchOpenLotsRequestCreateIdentifierType) ToPointer() *SearchOpenLotsRequestCreateIdentifierType {
	return &e
}

// SearchOpenLotsRequestCreate - Request message for retrieving open lots.
type SearchOpenLotsRequestCreate struct {
	// The security identifiers (see identifier_type) to filter open lots for one or more securities. If not specified, open lots meeting all other request criteria are returned regardless of security. (-- api-linter: core::0140::abbreviations=disabled   aip.dev/not-precedent: Aligning with apex api standard for identifiers)
	Identifier *string `json:"identifier,omitempty"`
	// The type of the identifier provided in the identifier field. Please include an identifier_type if you are using an identifier. (-- api-linter: core::0140::abbreviations=disabled   aip.dev/not-precedent: Aligning with apex api standard for identifiers)
	IdentifierType *SearchOpenLotsRequestCreateIdentifierType `json:"identifier_type,omitempty"`
	// Default page_size is 100, max page_size is 1000. Please note that the page_size must remain constant across all the requests when using a page_token to retrieve results of a given page.
	PageSize *int `json:"page_size,omitempty"`
	// page_token to retrieve results of a given page.
	PageToken *string `json:"page_token,omitempty"`
	// The parent resource name, which is the account_id. Format: accounts/{account}
	Parent string `json:"parent"`
	// Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following:
	//
	//  * A full date, with non-zero year, month, and day values * A month and day value, with a zero year, such as an anniversary * A year on its own, with zero month and day values * A year and month value, with a zero day, such as a credit card expiration date
	//
	//  Related types are [google.type.TimeOfDay][google.type.TimeOfDay] and `google.protobuf.Timestamp`.
	StartTradeDate *DateCreate `json:"start_trade_date,omitempty"`
}

func (o *SearchOpenLotsRequestCreate) GetIdentifier() *string {
	if o == nil {
		return nil
	}
	return o.Identifier
}

func (o *SearchOpenLotsRequestCreate) GetIdentifierType() *SearchOpenLotsRequestCreateIdentifierType {
	if o == nil {
		return nil
	}
	return o.IdentifierType
}

func (o *SearchOpenLotsRequestCreate) GetPageSize() *int {
	if o == nil {
		return nil
	}
	return o.PageSize
}

func (o *SearchOpenLotsRequestCreate) GetPageToken() *string {
	if o == nil {
		return nil
	}
	return o.PageToken
}

func (o *SearchOpenLotsRequestCreate) GetParent() string {
	if o == nil {
		return ""
	}
	return o.Parent
}

func (o *SearchOpenLotsRequestCreate) GetStartTradeDate() *DateCreate {
	if o == nil {
		return nil
	}
	return o.StartTradeDate
}
