// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SetAccountAccreditationTypeRequestCreateAccreditationType - The new accreditation type for the specified account.
type SetAccountAccreditationTypeRequestCreateAccreditationType string

const (
	SetAccountAccreditationTypeRequestCreateAccreditationTypeAccreditationTypeUnspecified SetAccountAccreditationTypeRequestCreateAccreditationType = "ACCREDITATION_TYPE_UNSPECIFIED"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeNetWorthGt1M                 SetAccountAccreditationTypeRequestCreateAccreditationType = "NET_WORTH_GT_1M"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeIndividualIncomeGt200K       SetAccountAccreditationTypeRequestCreateAccreditationType = "INDIVIDUAL_INCOME_GT_200K"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeJointIncomeGt300K            SetAccountAccreditationTypeRequestCreateAccreditationType = "JOINT_INCOME_GT_300K"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeProfessionDesignation        SetAccountAccreditationTypeRequestCreateAccreditationType = "PROFESSION_DESIGNATION"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeTrustGt5M                    SetAccountAccreditationTypeRequestCreateAccreditationType = "TRUST_GT_5M"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeGrantorsAccredited           SetAccountAccreditationTypeRequestCreateAccreditationType = "GRANTORS_ACCREDITED"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeEquityOwnersAccredited       SetAccountAccreditationTypeRequestCreateAccreditationType = "EQUITY_OWNERS_ACCREDITED"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeTotalAssetsGt5M              SetAccountAccreditationTypeRequestCreateAccreditationType = "TOTAL_ASSETS_GT_5M"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeInvestmentCompany            SetAccountAccreditationTypeRequestCreateAccreditationType = "INVESTMENT_COMPANY"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeSecOrExemptAdvisor           SetAccountAccreditationTypeRequestCreateAccreditationType = "SEC_OR_EXEMPT_ADVISOR"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeKnowledgeableEmployee        SetAccountAccreditationTypeRequestCreateAccreditationType = "KNOWLEDGEABLE_EMPLOYEE"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeKnowledgeableExecutive       SetAccountAccreditationTypeRequestCreateAccreditationType = "KNOWLEDGEABLE_EXECUTIVE"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeFamilyOfficeGt5M             SetAccountAccreditationTypeRequestCreateAccreditationType = "FAMILY_OFFICE_GT_5M"
	SetAccountAccreditationTypeRequestCreateAccreditationTypeNotAccredited                SetAccountAccreditationTypeRequestCreateAccreditationType = "NOT_ACCREDITED"
)

func (e SetAccountAccreditationTypeRequestCreateAccreditationType) ToPointer() *SetAccountAccreditationTypeRequestCreateAccreditationType {
	return &e
}

// SetAccountAccreditationTypeRequestCreate - Request for setting an account's accreditation type
type SetAccountAccreditationTypeRequestCreate struct {
	// The new accreditation type for the specified account.
	AccreditationType SetAccountAccreditationTypeRequestCreateAccreditationType `json:"accreditation_type"`
	// The resource name of the account accreditation. Note `{account}` will be the `account_id` value.
	//
	//  Format: accounts/{account}/accreditation
	Name string `json:"name"`
}

func (o *SetAccountAccreditationTypeRequestCreate) GetAccreditationType() SetAccountAccreditationTypeRequestCreateAccreditationType {
	if o == nil {
		return SetAccountAccreditationTypeRequestCreateAccreditationType("")
	}
	return o.AccreditationType
}

func (o *SetAccountAccreditationTypeRequestCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
