// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TransfersBeneficiaryCreate - A Check Beneficiary
type TransfersBeneficiaryCreate struct {
	// **Field Dependencies:**
	//
	// Account title is required for third party beneficiaries
	//
	// Required if `third_party` is `true`.
	AccountTitle *string `json:"account_title,omitempty"`
	// The data structure containing attributes describing the location of an underlying entity.
	Address *AddressCreate `json:"address,omitempty"`
	// Indicates if this beneficiary is a third party beneficiary. A check transfer is considered third party if the beneficiary is not the exact same person and/or entity that the funds originated from. This includes check transfers where the originator account is an individual account and the beneficiary account is a joint account
	ThirdParty *bool `json:"third_party,omitempty"`
}

func (o *TransfersBeneficiaryCreate) GetAccountTitle() *string {
	if o == nil {
		return nil
	}
	return o.AccountTitle
}

func (o *TransfersBeneficiaryCreate) GetAddress() *AddressCreate {
	if o == nil {
		return nil
	}
	return o.Address
}

func (o *TransfersBeneficiaryCreate) GetThirdParty() *bool {
	if o == nil {
		return nil
	}
	return o.ThirdParty
}
