workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Ascend OpenAPI:
        inputs:
            - location: ../ascend_uat_go.sdk.yaml
targets:
    sdk:
        target: go
        source: Ascend OpenAPI
        testing:
            enabled: true
            mockServer:
                enabled: false
