// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CancelWireWithdrawalRequestCreate - Request to cancel an existing wire withdrawal. The cancel will only succeed if the wire has not made it to the SendingToBank state
type CancelWireWithdrawalRequestCreate struct {
	// The name of the wire withdrawal to cancel
	Name string `json:"name"`
	// The reason why the wire withdrawal is being canceled
	Reason *string `json:"reason,omitempty"`
}

func (o *CancelWireWithdrawalRequestCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CancelWireWithdrawalRequestCreate) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}
