// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FinancialProfileCreate - Disclosure of the entity account owner's financial relationships and source of brokerage funds; facilitates the creation of the overall customer risk profile
type FinancialProfileCreate struct {
	// Bank names with whom the entity maintains a relationship with (e.g., accounts held with the bank)
	BankingRelationships []string `json:"banking_relationships"`
	// A customer-disclosed list of other Apex-held accounts owned by the Entity applicant at the time of this account's application; expressed as zero, one, or many account numbers
	OtherAccounts OtherAccountsCreate `json:"other_accounts"`
	// The primary source of funds that will be deposited to this account
	PrimarySourceOfDepositedFunds *string `json:"primary_source_of_deposited_funds,omitempty"`
}

func (o *FinancialProfileCreate) GetBankingRelationships() []string {
	if o == nil {
		return []string{}
	}
	return o.BankingRelationships
}

func (o *FinancialProfileCreate) GetOtherAccounts() OtherAccountsCreate {
	if o == nil {
		return OtherAccountsCreate{}
	}
	return o.OtherAccounts
}

func (o *FinancialProfileCreate) GetPrimarySourceOfDepositedFunds() *string {
	if o == nil {
		return nil
	}
	return o.PrimarySourceOfDepositedFunds
}
