// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ForceApproveAchDepositRequestCreate - Request to force approval of an existing ACH deposit that is pending review. FOR TESTING ONLY!
type ForceApproveAchDepositRequestCreate struct {
	// The name of the ACH deposit to force approve.
	Name string `json:"name"`
}

func (o *ForceApproveAchDepositRequestCreate) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
