// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListEnrollmentsResponse - The response to list Enrollments on an Account.
type ListEnrollmentsResponse struct {
	// The list of available enrollments
	Enrollments []Enrollment `json:"enrollments,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

func (o *ListEnrollmentsResponse) GetEnrollments() []Enrollment {
	if o == nil {
		return nil
	}
	return o.Enrollments
}

func (o *ListEnrollmentsResponse) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}
