// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ListAgreementsResponse - The response to list Agreements on an Account.
type ListAgreementsResponse struct {
	// The list of Agreements on an Account
	Agreements []Agreement `json:"agreements,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

func (o *ListAgreementsResponse) GetAgreements() []Agreement {
	if o == nil {
		return nil
	}
	return o.Agreements
}

func (o *ListAgreementsResponse) GetNextPageToken() *string {
	if o == nil {
		return nil
	}
	return o.NextPageToken
}
