// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UploadLink - Maps the correlation id to the signed link that can be used to upload the described document.
type UploadLink struct {
	// User-provided identifier that relates this signed link with the request used to get it
	ClientBatchSourceID *string `json:"client_batch_source_id,omitempty"`
	// Identifier for the upload link; This can be used to retrieve the document after it is uploaded
	Name *string `json:"name,omitempty"`
	// Signed link used to upload a document; The link expires one hour after being generated
	UploadLink *string `json:"upload_link,omitempty"`
}

func (o *UploadLink) GetClientBatchSourceID() *string {
	if o == nil {
		return nil
	}
	return o.ClientBatchSourceID
}

func (o *UploadLink) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UploadLink) GetUploadLink() *string {
	if o == nil {
		return nil
	}
	return o.UploadLink
}
